# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-18 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0004_fcm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('apns_certificate', models.TextField(blank=True, default='', help_text='Optional. Paste in the contents of your APNS certificate.')),
                ('gcm_api_key', models.TextField(blank=True, default='')),
                ('fcm_api_key', models.TextField(blank=True, default='')),
                ('wns_package_security_key', models.TextField(blank=True, default='')),
                ('wns_secret_key', models.TextField(blank=True, default='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
            ],
        ),
        migrations.AlterField(
            model_name='gcmdevice',
            name='cloud_message_type',
            field=models.CharField(choices=[('GCM', 'Google Cloud Message'), ('FCM', 'Firebase Cloud Message')], default='GCM', help_text='You should choose GCM or FCM', max_length=3, verbose_name='Cloud Message Type'),
        ),
        migrations.AddField(
            model_name='apnsdevice',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='push_notifications.Partner'),
        ),
        migrations.AddField(
            model_name='gcmdevice',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='push_notifications.Partner'),
        ),
        migrations.AddField(
            model_name='wnsdevice',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='push_notifications.Partner'),
        ),
    ]
