# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 19:17
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0005_applicationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcmdevice',
            name='device_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='ANDROID_ID / TelephonyManager.getDeviceId()', null=True, verbose_name='Device ID'),
        )
    ]
