# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0006_webpushdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcmdevice',
            name='registration_id',
            field=models.TextField(unique=True, verbose_name='Registration ID'),
        ),
    ]
