# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def migrate_device_id(apps, schema_editor):
    GCMDevice = apps.get_model("push_notifications", "GCMDevice")
    for device in GCMDevice.objects.filter(device_id__isnull=False):
        # previously stored as an unsigned integer
        device.device_uuid = uuid.UUID(int=device.device_id)
        device.save()


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0006_gcmdevice_device_uuid'),
    ]

    operations = [
        migrations.RunPython(migrate_device_id),
    ]
