# Generated by Django 3.2.8 on 2021-11-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0007_uniquesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpushdevice',
            name='browser',
            field=models.CharField(choices=[('CHROME', 'Chrome'), ('FIREFOX', 'Firefox'), ('OPERA', 'Opera'), ('EDGE', 'Edge')], default='CHROME', help_text='Currently only support to Chrome, Firefox, Edge and Opera browsers', max_length=10, verbose_name='Browser'),
        ),
    ]
