# Generated by Django 5.0.4 on 2024-04-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0009_alter_apnsdevice_device_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcmdevice',
            options={'verbose_name': 'FCM device'},
        ),
        migrations.AlterField(
            model_name='gcmdevice',
            name='cloud_message_type',
            field=models.CharField(choices=[('FCM', 'Firebase Cloud Message'), ('GCM', 'Google Cloud Message')], default='FCM', help_text='You should choose FCM, GCM is deprecated', max_length=3, verbose_name='Cloud Message Type'),
        ),
    ]
