# Generated by Django 5.1.7 on 2025-06-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0011_alter_apnsdevice_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpushdevice',
            name='browser',
            field=models.CharField(choices=[('CHROME', 'Chrome'), ('FIREFOX', 'Firefox'), ('OPERA', 'Opera'), ('EDGE', 'Edge'), ('SAFARI', 'Safari')], default='CHROME', help_text='Currently only support to Chrome, Firefox, Edge, Safari and Opera browsers', max_length=10, verbose_name='Browser'),
        ),
    ]
